### ISSUE TITLE
disable knock-out on reactions that are missing from the model

### ISSUE THREAD

**Issue by nkran** [DD-DeCaF/pathway-vis#17]
If knock-out is performed on reactions that are present on a map but not in a model, WS returns an error and some other things go bad as well.

Solution: disable action click on map elements that are not in the model.
Solution 2: handle removing unavailable reactions from the model on the backend as well.

**Comment by sgalkina** [comment]
This issue was moved to DD-DeCaF/metabolica-ui-map#23
