### ISSUE TITLE
As a user I want to see the first pathway predictions on the order of 1-5 seconds

### ISSUE THREAD

**Issue by phantomas1234** [DD-DeCaF/pathway-vis#35]

**Comment by phantomas1234** [comment]
From D9.1:

2.2.4 Heterologous pathways
This module supposes to scout all possible pathways from a defined substrate to a defined product based on a universal biochemical reaction database and an organism-specific GSMM. We were unable to test this module due to very long run time.

**Comment by sgalkina** [comment]
This issue was moved to DD-DeCaF/metabolica-ui-pathways#2
